dubbo:
  application:
    name: demo-consumer
    qos-enable: false
  protocol:
    name: dubbo
    port: 13002
  registry:
#    address: zookeeper://${zookeeper.address:127.0.0.1}:2181
    address: nacos://${nacos.host:127.0.0.1}:8848

